## Review Questions

#### Array Creation

Q05.01 Create an array of the numbers ```1```, ```5```, ```19```, ```30```

In [1]:
import numpy as np

a = np.array([1,5,19,30])
print(a)

[ 1  5 19 30]


Q05.02 Create an array of the numbers ```-3```, ```15```, ```0.001```, ```6.02e23```

In [2]:
b = np.array([-3,15,0.001,6.02e23])
print(b)

[-3.00e+00  1.50e+01  1.00e-03  6.02e+23]


Q05.03 Create an array of integers between -10 and 10

In [3]:
c = np.arange(-10,11)
print(c)

[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7
   8   9  10]


Q05.04 Create an array of 10 equally spaced angles between 0 and 2$\pi$

In [4]:
d = np.linspace(0,2*np.pi,10)
print(d)

[0.         0.6981317  1.3962634  2.0943951  2.7925268  3.4906585
 4.1887902  4.88692191 5.58505361 6.28318531]


Q05.05 Create an array of logarithmically spaced numbers between 1 and 1 million. Hint: remember to pass exponents to the ```np.logspace()``` function.

In [5]:
f = np.logspace(1,6,6)
print(f)

[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06]


Q05.06 Create an array of 20 random integers between 1 and 10

In [6]:
g = np.random.randint(1,11,20)
print(g)

[ 7  8 10 10  3  3  4  1 10  7  5  8  9  6  4  7  7  6  9  8]


Q05.07 Create an array of 30 random numbers with a normal distribution

In [7]:
h = np.random.randn(30)
print(h)

[ 0.56001026  0.43497158 -3.07254122  1.49117496 -0.60042265  0.20530545
 -0.36522797  0.138874    0.22891164 -0.50135172  0.53110863 -0.49882074
 -0.25474104 -0.73451207 -0.8152749   0.65575158 -1.37889465 -0.655284
 -1.57593082 -0.94872228  1.71188368 -1.20648031  0.3858553  -1.20990068
 -1.21422483  0.59350956 -0.14986626  0.92353358  0.50936535 -0.71430666]


Q05.08 Create an array of 30 random numbers with a normal distribution that has a mean $\mu$ of 78.5 and a standard deviation $\sigma$ of 5.2

In [8]:
mu = 78.5
sigma = 5.2

k = sigma * np.random.randn(30) + mu

print(k)

[79.28083024 80.67220709 72.61147359 85.06774107 72.69936161 84.30291831
 77.22118023 76.5079067  83.32524995 76.48768061 72.91506925 83.71487774
 78.4869765  75.38475077 77.93898385 84.94928036 80.22003337 69.50472901
 86.21482995 88.66762196 72.91024652 80.67153367 79.27792512 82.62521165
 86.70388058 70.9621571  82.53098071 83.80656746 80.31183708 68.14446881]


Q05.09 Create an array of 18 random floating-point numbers between 0 and 1

In [9]:
l = np.random.rand(18)
print(l)

[0.84670169 0.1597745  0.41980051 0.75153478 0.41644871 0.58476362
 0.10960059 0.1591185  0.85789279 0.59085377 0.87814886 0.36162054
 0.39969052 0.47624505 0.5574128  0.66442454 0.26383176 0.91244256]


Q05.10 Create an array of 18 random floating-point numbers between -1 and 0

In [10]:
n = -1*np.random.rand(18)
print(n)

[-0.9172642  -0.6131694  -0.7063505  -0.27534621 -0.63113137 -0.57634189
 -0.52376244 -0.81742478 -0.48755416 -0.27698799 -0.86372277 -0.33151523
 -0.23092399 -0.47935819 -0.84200965 -0.36642593 -0.36141487 -0.92290452]


Q05.11 Create an array of 18 random floating-point numbers between 0 and 10

In [11]:
m = 10*np.random.rand(18)
print(m)

[5.67869671 8.73872323 8.10213764 7.0363342  6.58938529 1.19319796
 8.19842769 1.041447   5.17304429 4.20468722 3.15203562 0.81396216
 4.54138411 3.61662237 7.21061741 6.51469439 7.59769764 6.80960902]


Q05.12 Create a variable $x$ that is an NumPy array which contains values 0, 0.1, 0.2, ..., 4.9, 5.0.  Hard coding the values one will be time-consuming, use a NumPy function to create the array instead.

In [12]:
x = np.arange(0,5.1,0.1)
print(x)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5. ]


Q05.13 Create a Python list containing the values 1, 2, 5.6, and 9 and store the Python list in a variable called ```x```.  Then create a NumPy array of the same values and store it in a variable called ```y```.

In [13]:
x = [1, 2, 5.6, 9]
y = np.array(x)
print(y)

[1.  2.  5.6 9. ]


Q05.14 Create an array called ```r``` of 200 evenly spaced numbers between and including 0 to 2$\pi$, then create an array ```y``` such that $y=10sin(3r)$.

In [14]:
r = np.linspace(0,2*np.pi,200)
y = 10*np.sin(3*r)
print(y)

[ 0.00000000e+00  9.45798078e-01  1.88311666e+00  2.80355229e+00
  3.69885285e+00  4.56099159e+00  5.38223906e+00  6.15523241e+00
  6.87304143e+00  7.52923064e+00  8.11791702e+00  8.63382275e+00
  9.07232251e+00  9.42948495e+00  9.70210796e+00  9.88774735e+00
  9.98473878e+00  9.99221269e+00  9.91010207e+00  9.73914308e+00
  9.48086844e+00  9.13759368e+00  8.71239643e+00  8.20908875e+00
  7.63218303e+00  6.98685146e+00  6.27887973e+00  5.51461512e+00
  4.70090958e+00  3.84505835e+00  2.95473450e+00  2.03792016e+00
  1.10283499e+00  1.57862420e-01 -7.88525454e-01 -1.72784385e+00
 -2.65167138e+00 -3.55172553e+00 -4.41993691e+00 -5.24852163e+00
 -6.03005107e+00 -6.75751849e+00 -7.42440181e+00 -8.02472214e+00
 -8.55309735e+00 -9.00479032e+00 -9.37575144e+00 -9.66265486e+00
 -9.86292838e+00 -9.97477646e+00 -9.99719634e+00 -9.92998700e+00
 -9.77375101e+00 -9.52988909e+00 -9.20058757e+00 -8.78879879e+00
 -8.29821460e+00 -7.73323331e+00 -7.09892022e+00 -6.40096223e+00
 -5.64561683e+00 -4.83965

Q05.15 Create an array of 25 regularly spaced numbers beginning at 10 and ending with 18.

In [15]:
p = np.linspace(10,18,25)
print(p)

[10.         10.33333333 10.66666667 11.         11.33333333 11.66666667
 12.         12.33333333 12.66666667 13.         13.33333333 13.66666667
 14.         14.33333333 14.66666667 15.         15.33333333 15.66666667
 16.         16.33333333 16.66666667 17.         17.33333333 17.66666667
 18.        ]


Q05.16 Create an array of regularly spaced numbers beginning at 10, ending with 18.4 using an increment of 0.6.

In [16]:
q = np.arange(10,18.4+0.6,0.6)
print(q)

[10.  10.6 11.2 11.8 12.4 13.  13.6 14.2 14.8 15.4 16.  16.6 17.2 17.8
 18.4]


#### Array Manipulation

Q05.20 Create a NumPy array called ```A``` and store the values 5, 8, -8, 99, and 0 in array ```A``` in a single row, five columns. Reshape ```A``` to an array with one column and five rows.

In [17]:
A = np.array([5,8,-8,99,0])
print(A)
B = A.reshape((5,1))
print(B)

[ 5  8 -8 99  0]
[[ 5]
 [ 8]
 [-8]
 [99]
 [ 0]]


Q05.21 Create a NumPy array called ```B``` and store the values 1, 2, 3, 4, 5 as floats, not integers.

In [18]:
B = np.array([1,2,3,4,5], dtype=np.float64)
print(B)

[1. 2. 3. 4. 5.]


#### Array Slicing

Q05.30 Create an array ```B``` that contains integers 0 to 24 (including 24) in one row.  Then reshape ```B``` into a 5 row by 5 column array.

(a) Extract the 2nd row from ```B```.  Store it as a one column array called ```x```.

(b) Store the number of elements in array ```x``` in a new variable called ```y```. 

(c) Extract the last column of ```B``` and store it in an array called ```z```.  

(d) Store a transposed version of ```B``` in an array called ```t```.

In [19]:
B = np.arange(0,25)
B = B.reshape((5,5))
print(B)

#(a)
x = B[1,:]
print(x)

#(b)
y = len(B)
print(y)

#(c)
z = B[:,-1]
print(z)

#(d)
t = B.transpose()
print(t)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[5 6 7 8 9]
5
[ 4  9 14 19 24]
[[ 0  5 10 15 20]
 [ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]]


Q05.31 Run the following code to create a NumPy array ```C```

```C = np.array(range(11)) + 5```

(a) Extract the 4th value in array ```C``` into a variable called ```x```.

(b) Extract the 2nd-to-last value in array ```C``` into a variable called ```y```.

(c) Extract the values from array ```C``` starting from the 3rd value up to and including the 7th value into a variable called ```z```.

In [20]:
C = np.array(range(11)) + 5
print(C)

# (a)
x = C[3]
print(x)

# (b)
y = C[-2]
print(y)

# (c)
z = C[2:7]
print(z)

[ 5  6  7  8  9 10 11 12 13 14 15]
8
14
[ 7  8  9 10 11]


Q05.32 Run the following code to create a NumPy array ```D```

```D = np.array(range(18)) + 3```

(a) Extract every other value from array ```D``` starting from the 2nd value through the 10th value.  Store the result in a variable called ```x```.

(b) Extract every other value from array ```D``` starting from the 10th value through the 2nd value.  Store the result a variable called ```y```.

(c) Create a variable ```z``` that contains all of the values in ```D``` in reverse order.

In [21]:
D = np.array(range(18)) + 3
print(D)

# (a)
x = D[1:10:2]
print(x)

# (b)
y = D[9:0:-2]
print(y)

# (c)
z = D[::-1]
print(z)

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 4  6  8 10 12]
[12 10  8  6  4]
[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3]


Q05.33 The 1D NumPy array ```F``` is defined below.  But construct your code to work with any 1D NumPy array filled with numbers.

```F = np.array([5, -4.7, 99, 50, 6, -1, 0, 50, -78, 27, 10])```

(a) Select all the elements from ```F``` that are greater than ```5``` and store them in ```x```.

(b) Select all of the elements from ```F``` that are between ```5``` and ```30```.  Store them in ```y```.

(c) Select all of the elements from ```F``` that are between ```5``` and ```30``` or that are equal to ```50```.  Store them in ```z```.

Hint: To perform the logical ```OR``` or ```AND``` operations, on boolean arrays of the same dimensions, NumPy functions are needed.  The standard Python ```"or"``` and ```"and"``` will not work. 

Hint: You can use either logical indexing or ```np.where()``` to get the appropriate values from ```A```.

In [22]:
F = np.array([5, -4.7, 99, 50, 6, -1, 0, 50, -78, 27, 10])
print(F)

# (a)
x = F[F>5]
print(x)

# (b)
m1 = np.logical_and(5<F,F<50)
y = F[m1]
print(y)

# (c)
m1 = np.logical_and(5<F,F<50)
m2 = F==50.0
m3 = np.logical_or(m1,m2)
z = F[m3]
print(z)

[  5.   -4.7  99.   50.    6.   -1.    0.   50.  -78.   27.   10. ]
[99. 50.  6. 50. 27. 10.]
[ 6. 27. 10.]
[50.  6. 50. 27. 10.]


Q05.34 The 1D NumPy array ```B``` is defined below.  But your code should work with any 1D NumPy array filled with numeric values.

```G = np.array([5, -4.7, 99, 50, 6, -1, 0, 50, -78, 27, 10])```

(a) Select all of the positive numbers in ```G``` and store them in ```x```.

(b) Select all the numbers in ```G``` between ```0``` and  ```30``` and store them in ```y```.

(c) Select all of the numbers in ```G``` that are either less than ```-50``` or greater than ```50``` and store them in ```z```.

In [23]:
G = np.array([5, -4.7, 99, 50, 6, -1, 0, 50, -78, 27, 10])

print(G)

# (a)
x = G[F>0]
print(x)

# (b)
m1 = np.logical_and(0<G,G<30)
y = F[m1]
print(y)

# (c)
m2 = np.logical_or(G<-50,50<G)
z = F[m2]
print(z)

[  5.   -4.7  99.   50.    6.   -1.    0.   50.  -78.   27.   10. ]
[ 5. 99. 50.  6. 50. 27. 10.]
[ 5.  6. 27. 10.]
[ 99. -78.]


Q05.35 Define an integer ```c``` which is a random integer between ```100``` and ```999``` (including ```100``` and ```999```)

(a) pull the first digit out of ```c``` and assign it to the variable ```x```

(b) pull the second digit out of ```c``` and assign it to the variable ```y```

(c) pull the third digit out of ```c``` and assign it to the variable ```z```.

In [24]:
c = np.random.randint(100,1000,1)
print(c)

# (a)
s = np.array2string(c)
print(s)
x = s[1]
print(x)

# (b)
y = s[2]
print(y)

# (c)
z = s[3]
print(z)

[951]
[951]
9
5
1


#### Meshgrids

Q05.40 Create two 2D arrays from the two 1D arrays below using NumPy's ```np.meshgrid()``` function. 

```text

x = [0.0, 0.1, 0.2, 0.3, 0.4, 0.5]

y = [0, 2, 4, 6]
```

In [25]:
x = [0.0, 0.1, 0.2, 0.3, 0.4, 0.5]

y = [0, 2, 4, 6]

X1, Y1 = np.meshgrid(x,y)
print(X1)
print(Y1)

[[0.  0.1 0.2 0.3 0.4 0.5]
 [0.  0.1 0.2 0.3 0.4 0.5]
 [0.  0.1 0.2 0.3 0.4 0.5]
 [0.  0.1 0.2 0.3 0.4 0.5]]
[[0 0 0 0 0 0]
 [2 2 2 2 2 2]
 [4 4 4 4 4 4]
 [6 6 6 6 6 6]]


Q05.41 Create a meshgrid of the two arrays below:

```text

x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

y = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
```

Use element-wise multiplication to multiply each element in the first resulting 2D array with the corresponding element is the second array to build a multiplication table.

In [26]:
x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

y = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

X1, Y1 = np.meshgrid(x,y)
print(X1)
print(Y1)

prod = X1*Y1
print(prod)

[[ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]]
[[ 1  1  1  1  1  1  1  1  1  1]
 [ 2  2  2  2  2  2  2  2  2  2]
 [ 3  3  3  3  3  3  3  3  3  3]
 [ 4  4  4  4  4  4  4  4  4  4]
 [ 5  5  5  5  5  5  5  5  5  5]
 [ 6  6  6  6  6  6  6  6  6  6]
 [ 7  7  7  7  7  7  7  7  7  7]
 [ 8  8  8  8  8  8  8  8  8  8]
 [ 9  9  9  9  9  9  9  9  9  9]
 [10 10 10 10 10 10 10 10 10 10]]
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72

#### Array Operations

Q05.50 Create the two arrays below and perform each calculation.

```a = [2 4 6]```

```b = [-1 0 1]```

(a) $a + b$

(b) $1.5a -2b$

(c) $0.5ab$

(d) $\frac{b^2}{a}$

In [27]:
a = np.array([2, 4, 6])

b = np.array([-1, 0, 1])

# (a)
ans1 = a + b
print(ans1)

# (b)
ans2 = 1.5*a - 2*b
print(ans2)

# (c)
ans3 = 0.5*a*b
print(ans3)

# (d)
ans4 = b**2/a
print(ans4)

[1 4 7]
[5. 6. 7.]
[-1.  0.  3.]
[0.5        0.         0.16666667]


Q05.51 Create an array of angles between (and including) 0 and 2$\pi$ radians in increments of $\pi/2$ radians.

(a) Calculate the sine of each angle in the array

(b) Calculate the cosine of each angle in the array

(c) Convert each angle in the array to degrees

In [28]:
a = np.arange(0,2*np.pi+np.pi/2,np.pi/2)
print(a)

# (a)
ans1 = np.sin(a)
print(ans1)

# (b)
ans2 = np.cos(a)
print(ans2)

# (c)
ans3 = np.degrees(a)
print(ans3)

[0.         1.57079633 3.14159265 4.71238898 6.28318531]
[ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00
 -2.4492936e-16]
[ 1.0000000e+00  6.1232340e-17 -1.0000000e+00 -1.8369702e-16
  1.0000000e+00]
[  0.  90. 180. 270. 360.]


Q05.52 Create the two arrays ```F1```, ```F2``` below and then perform the following operations.

```F1 = [-1, 0, 2]```

```F2 = [5, -2, 0]```

(a) Calculate the dot product of ```F1``` and ```F2```

(b) Calculate cross product of ```F1``` and ```F2```

(c) Calculate the element-wise product (element-wise multiplication of ```F1``` and ```F2```)

In [29]:
F1 = np.array([2, 4, 6])

F2 = np.array([-1, 0, 1])

print(F1)
print(F2)

# (a)
ans1 = np.dot(F1,F2)
print(ans1)

# (b)
ans2 = np.cross(F1,F2)
print(ans2)

# (c)
ans3 = F1*F2
print(ans3)

[2 4 6]
[-1  0  1]
4
[ 4 -8  4]
[-2  0  6]


Q05.53 Compute all possible prices of flooring that can have lengths of ```2```, ```4```, ```6```, and ```8``` meters and widths of ```1```, ```1.5```, and ```2``` meters if the flooring costs \$32.19 per square meter. Store the result in a 2D array. The lengths should increase from top to bottom and widths should increase from left to right.

In [30]:
l = np.array([2,4,6,8])
w = np.array([1,1.5,2])

W,L = np.meshgrid(w,l)
print(L)
print(W)

prices = L*W*32.19
print(prices)

[[2 2 2]
 [4 4 4]
 [6 6 6]
 [8 8 8]]
[[1.  1.5 2. ]
 [1.  1.5 2. ]
 [1.  1.5 2. ]
 [1.  1.5 2. ]]
[[ 64.38  96.57 128.76]
 [128.76 193.14 257.52]
 [193.14 289.71 386.28]
 [257.52 386.28 515.04]]


Q05.54 Create array ```H``` defined by the code below:

```H = np.array([-5, 10, 12, 500, 20, 10, -46, 16])```

(a) Create a boolean array ```x``` based on the variable ```H```.  ```x``` should be ```True``` everywhere ```H``` equals ```10``` and ```False``` everywhere else.

(b) Create a boolean array ```y``` based on the variable ```H```.  ```y``` should be ```True``` everywhere ```H``` is not equal to ```10```.  ```y``` should be ```False``` everywhere else.

(c) Create a boolean array ```z``` based on the variable ```H```.  ```z``` should be ```True``` everywhere ```H``` is less than or equal to ```20```.  ```z``` should be ```False``` everywhere else.

In [31]:
H = np.array([-5, 10, 12, 500, 20, 10, -46, 16])

print(H)

# (a)
x = H==10
print(x)

# (b)
y = H!=10
print(y)

# (c)
z = H<=20
print(z)

[ -5  10  12 500  20  10 -46  16]
[False  True False False False  True False False]
[ True False  True  True  True False  True  True]
[ True  True  True False  True  True  True  True]


Q05.55 Create array ```J``` using the code below:

```
J = np.array(range(7*5)).reshape((7, 5))
J[4, 3] = 500
```

(a) Store the row index of the number ```500``` in a variable called ```row_500```.

(b) Store the column index of the number ```500``` in a variable called ```col_500```.

In [32]:
J = np.array(range(7*5)).reshape((7, 5))
J[4, 3] = 500
print(J)

# (a)
row_col = np.where(J==500)
row_500 = row_col[0][0]
print(row_500)

# (b)
row_col = np.where(J==500)
col_500 = row_col[1][0]
print(col_500)

[[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]
 [ 20  21  22 500  24]
 [ 25  26  27  28  29]
 [ 30  31  32  33  34]]
4
3


Q05.56 Create array ```K``` using the code below:

```
K = np.random.randint(100, 500, 7*7).reshape(7, 7)
K[2, 6] = 250
```

(a) Extract all of the values from ```K``` that are greater or equal to ```250``` and store them in an array called ```x```. 

(b) Extract all of the values from ```K``` that are less than ```250``` and store them in an array called ```y```.

(c) Programmatically determine which column and which row the number ```250``` is stored inside of array ```K```.

In [33]:
K = np.random.randint(100, 500, 7*7).reshape(7, 7)
K[2, 6] = 250
print(K)

# (a)
m1 = K>=250
x = K[m1]
print(x)

# (b)
m2 = K<250
y = K[m2]
print(y)

# (c)
loc_row_col = np.where(K==250)
row = loc_row_col[0][0]
print("row:", row)
col = loc_row_col[1][0]
print("col", col)

[[241 147 408 204 410 176 232]
 [399 156 361 496 187 245 494]
 [162 238 343 139 309 244 250]
 [148 481 388 484 235 302 173]
 [391 326 457 160 311 462 153]
 [210 134 495 304 450 287 138]
 [251 356 467 443 116 467 480]]
[408 410 399 361 496 494 343 309 250 481 388 484 302 391 326 457 311 462
 495 304 450 287 251 356 467 443 467 480]
[241 147 204 176 232 156 187 245 162 238 139 244 148 235 173 160 153 210
 134 138 116]
row: 2
col 6


#### Systems of Linear Equations

Q05.70 Use the system of linear equations below to calculate the values of $x$ and $y$.

$$ 4x - 2y = -42 $$

$$ -6x + y = 31 $$

In [34]:
A = np.array([[4, -2], [-6, 1]])
b = np.array([-42, 31])
ans = np.linalg.solve(A, b)
x = ans[0]
print("x=", x)
y = ans[1]
print("y=", y)
check1 = 4*x - 2*y
print("check 1st equation: ", check1)
check2 = -6*x + y
print("check 2nd equation: ", check2)

x= -2.5
y= 16.0
check 1st equation:  -42.0
check 2nd equation:  31.0


Q05.71 Use the system of linear equations below to calculate the values of $x$, $y$, and $z$.

$$ \frac{x}{2} +2y - z = 5 $$

$$ x + 3y - 4z = -1 $$

$$ -x - 3y + 2z = -5 $$

In [35]:
A = np.array([[1/2, 2, -1], [1, 3, -4], [-1, -3, 2]])
b = np.array([5, -1, -5])
ans = np.linalg.solve(A, b)
x = ans[0]
print("x=", x)
y = ans[1]
print("y=", y)
z = ans[2]
print("z=", z)

check1 = 0.5*x + 2*y - z
print("check 1st equation: ", check1)
check2 = x + 3*y - 4*z
print("check 2nd equation: ", check2)
check3 = -x + -3*y + 2*z
print("check 3nd equation: ", check3)

x= -4.0
y= 5.0
z= 3.0
check 1st equation:  5.0
check 2nd equation:  -1.0
check 3nd equation:  -5.0


Q05.72 Use the system of linear equations below to calculate the values of $F_1$, $F_2$, and $F_3$.

$$ 2F_1 + 3F_2 - F_3 = -9 $$

$$ -F_1 + 2F_2 + 5F_3 = -20 $$

$$ F_1 - F_2 - F_3 = 1 $$

In [36]:
A = np.array([[2, 3, -1], [-1, 2, 5], [1, -1, -1]])
b = np.array([-9, -20, -1])
ans = np.linalg.solve(A, b)
F1 = ans[0]
print("F1=", F1)
F2 = ans[1]
print("F2=", F2)
F3 = ans[2]
print("F3=", F3)

check1 = 2*F1 + 3*F2 -1*F3
print("check 1st equation: ", check1)
check2 = -1*F1 + 2*F2 + 5*F3
print("check 2nd equation: ", check2)
check3 = F1 - F2 - F3
print("check 3nd equation: ", check3)

F1= -6.526315789473685
F2= -0.36842105263157887
F3= -5.157894736842105
check 1st equation:  -9.0
check 2nd equation:  -20.0
check 3nd equation:  -1.0000000000000009
