## Review Questions

#### Array Creation

Q05.01 Create an array of the numbers ```1```, ```5```, ```19```, ```30```

In [1]:
import numpy as np

a = np.array([1,5,19,30])
print(a)

[ 1  5 19 30]


Q05.02 Create an array of the numbers ```-3```, ```15```, ```0.001```, ```6.02e23```

In [2]:
b = np.array([-3,15,0.001,6.02e23])
print(b)

[-3.00e+00  1.50e+01  1.00e-03  6.02e+23]


Q05.03 Create an array of integers between -10 and 10

In [3]:
c = np.arange(-10,11)
print(c)

[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7
   8   9  10]


Q05.04 Create an array of 10 equally spaced angles between 0 and 2$\pi$

In [4]:
d = np.linspace(0,2*np.pi,10)
print(d)

[0.         0.6981317  1.3962634  2.0943951  2.7925268  3.4906585
 4.1887902  4.88692191 5.58505361 6.28318531]


Q05.05 Create an array of logarithmically spaced numbers between 1 and 1 million. Hint: remember to pass exponents to the ```np.logspace()``` function.

In [5]:
f = np.logspace(1,6,6)
print(f)

[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06]


Q05.06 Create an array of 20 random integers between 1 and 10

In [6]:
g = np.random.randint(1,11,20)
print(g)

[ 7  7  3  7  2  8  1  9 10  4  2  4  9  2  9  7  6  4  4  1]


Q05.07 Create an array of 30 random numbers with a normal distribution

In [7]:
h = np.random.randn(30)
print(h)

[-1.1363547  -0.89235868  0.82831741 -0.18308728  1.01428786 -0.9679404
 -2.41588734 -0.06209297  0.32505607 -2.17051132 -0.56989     1.07829013
  0.998437    0.3255444   0.04981193  1.37953863 -0.18950461  0.09482425
  0.02835773  0.28255577 -1.0754257  -1.04860385  1.25914887 -0.45251674
 -0.29253135 -1.26446054  1.30967326  1.42511327 -0.11890615 -0.08312011]


Q05.08 Create an array of 30 random numbers with a normal distribution that has a mean $\mu$ of 78.5 and a standard deviation $\sigma$ of 5.2

In [8]:
mu = 78.5
sigma = 5.2

k = sigma * np.random.randn(30) + mu

print(k)

[73.58115971 82.97149291 66.35002624 82.00141119 89.69587592 81.07237047
 84.85716537 70.57311004 81.30944753 70.29504082 74.27689179 77.72736915
 71.70014036 78.76623259 78.09722621 75.75533513 81.56206371 78.49650166
 80.4466932  91.15508244 74.10206327 93.80684598 79.77140995 77.12964918
 80.5682737  72.07080882 73.22240565 75.33852799 83.01877744 81.30292844]


Q05.09 Create an array of 18 random floating-point numbers between 0 and 1

In [9]:
l = np.random.rand(18)
print(l)

[0.65125216 0.95608941 0.7246307  0.15660673 0.94698073 0.15778789
 0.54047253 0.29515821 0.66237045 0.61038193 0.38795421 0.59022246
 0.16654063 0.01651174 0.24146675 0.73181695 0.97041838 0.50892666]


Q05.10 Create an array of 18 random floating-point numbers between -1 and 0

In [10]:
n = -1*np.random.rand(18)
print(n)

[-0.16331814 -0.67646319 -0.84350205 -0.01673595 -0.025672   -0.4969675
 -0.53962762 -0.17868182 -0.53935046 -0.28623898 -0.28306699 -0.81882191
 -0.70721524 -0.04889104 -0.65969978 -0.01671194 -0.61946659 -0.32932804]


Q05.11 Create an array of 18 random floating-point numbers between 0 and 10

In [11]:
m = 10*np.random.rand(18)
print(m)

[2.75188531 0.31134696 7.33109147 1.89112273 0.14667789 2.55353769
 9.10386566 9.05156939 3.27194715 1.64625077 5.08956832 7.65051832
 3.11687402 5.37902495 8.88874926 4.06276783 5.6742423  0.55083148]


Q05.12 Create a variable $x$ that is an NumPy array which contains values 0, 0.1, 0.2, ..., 4.9, 5.0.  Hard coding the values one will be time-consuming, use a NumPy function to create the array instead.

In [12]:
x = np.arange(0,5.1,0.1)
print(x)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5. ]


Q05.13 Create a Python list containing the values 1, 2, 5.6, and 9 and store the Python list in a variable called ```x```.  Then create a NumPy array of the same values and store it in a variable called ```y```.

In [13]:
x = [1, 2, 5.6, 9]
y = np.array(x)
print(y)

[1.  2.  5.6 9. ]


Q05.14 Create an array called ```r``` of 200 evenly spaced numbers between and including 0 to 2$\pi$, then create an array ```y``` such that $y=10sin(3r)$.

In [14]:
r = np.linspace(0,2*np.pi,200)
y = 10*np.sin(3*r)
print(y)

[ 0.00000000e+00  9.45798078e-01  1.88311666e+00  2.80355229e+00
  3.69885285e+00  4.56099159e+00  5.38223906e+00  6.15523241e+00
  6.87304143e+00  7.52923064e+00  8.11791702e+00  8.63382275e+00
  9.07232251e+00  9.42948495e+00  9.70210796e+00  9.88774735e+00
  9.98473878e+00  9.99221269e+00  9.91010207e+00  9.73914308e+00
  9.48086844e+00  9.13759368e+00  8.71239643e+00  8.20908875e+00
  7.63218303e+00  6.98685146e+00  6.27887973e+00  5.51461512e+00
  4.70090958e+00  3.84505835e+00  2.95473450e+00  2.03792016e+00
  1.10283499e+00  1.57862420e-01 -7.88525454e-01 -1.72784385e+00
 -2.65167138e+00 -3.55172553e+00 -4.41993691e+00 -5.24852163e+00
 -6.03005107e+00 -6.75751849e+00 -7.42440181e+00 -8.02472214e+00
 -8.55309735e+00 -9.00479032e+00 -9.37575144e+00 -9.66265486e+00
 -9.86292838e+00 -9.97477646e+00 -9.99719634e+00 -9.92998700e+00
 -9.77375101e+00 -9.52988909e+00 -9.20058757e+00 -8.78879879e+00
 -8.29821460e+00 -7.73323331e+00 -7.09892022e+00 -6.40096223e+00
 -5.64561683e+00 -4.83965

Q05.15 Create an array of 25 regularly spaced numbers beginning at 10 and ending with 18.

In [15]:
p = np.linspace(10,18,25)
print(p)

[10.         10.33333333 10.66666667 11.         11.33333333 11.66666667
 12.         12.33333333 12.66666667 13.         13.33333333 13.66666667
 14.         14.33333333 14.66666667 15.         15.33333333 15.66666667
 16.         16.33333333 16.66666667 17.         17.33333333 17.66666667
 18.        ]


Q05.16 Create an array of regularly spaced numbers beginning at 10, ending with 18.4 using an increment of 0.6.

In [16]:
q = np.arange(10,18.4+0.6,0.6)
print(q)

[10.  10.6 11.2 11.8 12.4 13.  13.6 14.2 14.8 15.4 16.  16.6 17.2 17.8
 18.4]


#### Array Manipulation

Q05.20 Create a NumPy array called ```A``` and store the values 5, 8, -8, 99, and 0 in array ```A``` in a single row, five columns. Reshape ```A``` to an array with one column and five rows.

In [17]:
A = np.array([5,8,-8,99,0])
print(A)
B = A.reshape((5,1))
print(B)

[ 5  8 -8 99  0]
[[ 5]
 [ 8]
 [-8]
 [99]
 [ 0]]


Q05.21 Create a NumPy array called ```B``` and store the values 1, 2, 3, 4, 5 as floats, not integers.

In [18]:
B = np.array([1,2,3,4,5], dtype=np.float64)
print(B)

[1. 2. 3. 4. 5.]


#### Array Slicing

Q05.30 Create an array ```B``` that contains integers 0 to 24 (including 24) in one row.  Then reshape ```B``` into a 5 row by 5 column array.

(a) Extract the 2nd row from ```B```.  Store it as a one column array called ```x```.

(b) Store the number of elements in array ```x``` in a new variable called ```y```. 

(c) Extract the last column of ```B``` and store it in an array called ```z```.  

(d) Store a transposed version of ```B``` in an array called ```t```.

In [19]:
B = np.arange(0,25)
B = B.reshape((5,5))
print(B)

#(a)
x = B[1,:]
print(x)

#(b)
y = len(B)
print(y)

#(c)
z = B[:,-1]
print(z)

#(d)
t = B.transpose()
print(t)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[5 6 7 8 9]
5
[ 4  9 14 19 24]
[[ 0  5 10 15 20]
 [ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]]


Q05.31 Run the following code to create a NumPy array ```C```

```C = np.array(range(11)) + 5```

(a) Extract the 4th value in array ```C``` into a variable called ```x```.

(b) Extract the 2nd-to-last value in array ```C``` into a variable called ```y```.

(c) Extract the values from array ```C``` starting from the 3rd value up to and including the 7th value into a variable called ```z```.

Q05.32 Run the following code to create a NumPy array ```D```

```D = np.array(range(18)) + 3```

(a) Extract every other value from array ```D``` starting from the 2nd value through the 10th value.  Store the result in a variable called ```x```.

(b) Extract every other value from array ```D``` starting from the 10th value through the 2nd value.  Store the result a variable called ```y```.

(c) Create a variable ```z``` that contains all of the values in ```D``` in reverse order.

Q05.33 The 1D NumPy array ```F``` is defined below.  But construct your code to work with any 1D NumPy array filled with numbers.

```F = np.array([5, -4.7, 99, 50, 6, -1, 0, 50, -78, 27, 10])```

(a) Select all the elements from ```F``` that are greater than ```5``` and store them in ```x```.

(b) Select all of the elements from ```F``` that are between ```5``` and ```30```.  Store them in ```y```.

(c) Select all of the elements from ```F``` that are between ```5``` and ```30``` or that are equal to ```50```.  Store them in ```z```.

Hint: To perform the logical ```OR``` or ```AND``` operations, on boolean arrays of the same dimensions, NumPy functions are needed.  The standard Python ```"or"``` and ```"and"``` will not work. 

Hint: You can use either logical indexing or ```np.where()``` to get the appropriate values from ```A```.

Q05.34 The 1D NumPy array ```B``` is defined below.  But your code should work with any 1D NumPy array filled with numeric values.

```G = np.array([5, -4.7, 99, 50, 6, -1, 0, 50, -78, 27, 10])```

(a) Select all of the positive numbers in ```G``` and store them in ```x```.

(b) Select all the numbers in ```G``` between ```0``` and  ```30``` and store them in ```y```.

(c) Select all of the numbers in ```G``` that are either less than ```-50``` or greater than ```50``` and store them in ```z```.

Q05.35 Define an integer ```c``` which is a random integer between ```100``` and ```999``` (including ```100``` and ```999```)

(a) pull the first digit out of ```c``` and assign it to the variable ```x```

(b) pull the second digit out of ```c``` and assign it to the variable ```y```

(c) pull the third digit out of ```c``` and assign it to the variable ```z```.

#### Meshgrids

Q05.40 Create two 2D arrays from the two 1D arrays below using NumPy's ```np.meshgrid()``` function. 

```text

x = [0.0, 0.1, 0.2, 0.3, 0.4, 0.5]

y = [0, 2, 4, 6]
```

Q05.41 Create a meshgrid of the two arrays below:

```text

x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

y = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
```

Use element-wise multiplication to multiply each element in the first resulting 2D array with the corresponding element is the second array to build a multiplication table.

#### Array Operations

Q05.50 Create the two arrays below and perform each calculation.

```a = [2 4 6]```

```b = [-1 0 1]```

(a) $a + b$

(b) $1.5a -2b$

(c) $0.5ab$

(d) $\frac{b^2}{a}$


Q05.51 Create an array of angles between (and including) 0 and 2$\pi$ radians in increments of $\pi/2$ radians.

(a) Calculate the sine of each angle in the array

(b) Calculate the cosine of each angle in the array

(c) Convert each angle in the array to degrees

Q05.52 Create the two arrays ```F1```, ```F2``` below and then perform the following operations.

```F1 = [-1, 0, 2]```

```F2 = [5, -2, 0]```

(a) Calculate the dot product of ```F1``` and ```F2```

(b) Calculate cross product of ```F1``` and ```F2```

(c) Calculate the element-wise product (element-wise multiplication of ```F1``` and ```F2```)

Q05.53 Compute all possible prices of flooring that can have lengths of ```2```, ```4```, ```6```, and ```8``` meters and widths of ```1```, ```1.5```, and ```2``` meters if the flooring costs \$32.19 per square meter. Store the result in a 2D array. The lengths should increase from top to bottom and widths should increase from left to right.

Q05.54 Create array ```H``` defined by the code below:

```H = np.array([-5, 10, 12, 500, 20, 10, -46, 16])```

(a) Create a boolean array ```x``` based on the variable ```H```.  ```x``` should be ```True``` everywhere ```H``` equals ```10``` and ```False``` everywhere else.

(b) Create a boolean array ```y``` based on the variable ```H```.  ```y``` should be ```True``` everywhere ```H``` is not equal to ```10```.  ```y``` should be ```False``` everywhere else.

(c) Create a boolean array ```z``` based on the variable ```H```.  ```z``` should be ```True``` everywhere ```H``` is less than or equal to ```20```.  ```z``` should be ```False``` everywhere else.

Q05.55 Create array ```J``` using the code below:

```
J = np.array(range(7*5)).reshape((7, 5))
J[4, 3] = 500
```

(a) Store the row index of the number ```500``` in a variable called ```row_500```.

(b) Store the column index of the number ```500``` in a variable called ```col_500```.

Q05.56 Create array ```K``` using the code below:

```
K = np.random.randint(100, 500, 7*7).reshape(7, 7)
K[2, 6] = 250
```

(a) Extract all of the values from ```K``` that are greater or equal to ```250``` and store them in an array called ```x```. 

(b) Extract all of the values from ```K``` that are less than ```250``` and store them in an array called ```y```.

(c) Programmatically determine which column and which row the number ```250``` is stored inside of array ```K```.

#### Systems of Linear Equations

Q05.70 Use the system of linear equations below to calculate the values of $x$ and $y$.

$$ 4x - 2y = -42 $$

$$ -6x + y = 31 $$

Q05.71 Use the system of linear equations below to calculate the values of $x$, $y$, and $z$.

$$ \frac{x}{2} +2y - z = 5 $$

$$ x + 3y - 4z = -1 $$

$$ -x - 3y + 2z = -5 $$

Q05.72 Use the system of linear equations below to calculate the values of $F_1$, $F_2$, and $F_3$.

$$ 2F_1 + 3F_2 - F_3 = -9 $$

$$ -F_1 + 2F_2 + 5F_3 = -20 $$

$$ F_1 - F_2 - F_3 = 1 $$
